### ISSUE TITLE
cutechess-cli sometimes reports illegal moves in the PV

### ISSUE THREAD

**Issue by JasonCreighton** [JasonCreighton/snowy#1]
When running tournaments, I've noticed cutechess-cli sometimes reports an illegal move in the PV. I've not seen it report an actual attempt to play an illegal move.

The move always seems to be a castling move.

**Comment by ghost** [comment]
Jason,

didn't you see illegal pawn moves from the 2nd/7th rank? I'm not a programmer and currently I can't test it (in about 10 hours I'll be able to do it), but it seems that in Board.cpp lines #258 and #259 allow two-square distances of capturing, because FindMovesInDirection functions can absorb moveDistance=2 from line #250.

**Comment by JasonCreighton** [comment]
That is an interesting case! However, it is actually safe, because when the pawn captures are generated, the movementAllowed parameter of FindMovesInDirection is false, which will cause it to bail out after one iteration, never generated pawn captures of distance two. I do agree the code is confusing on this point, as there is no need to pass the calculated movementDistance when considering captures. I will update the code to hopefully be a little more clear.

Regarding this illegal castling moves issue, I suspect some sort of transposition table bug, because at present I extract the PV by walking the hash table as far as I can after a search completes.

**Comment by JasonCreighton** [comment]
For future reference, a position and set of moves to reproduce the issue:

`position fen r2qkb1r/1b1n1ppp/2p1pn2/p7/1p1PN3/P2BPN2/1P3PPP/R1BQK2R w KQkq - 0 1 moves e1g1 f6e4 d3e4 d7f6 e4d3 f8d6 a3b4 a5b4 a1a8 d8a8 e3e4 d6e7 e4e5 f6d5 c1g5 f7f6 e5f6 g7f6 g5h6`
