### ISSUE TITLE
wrong update of the 50-move rule counter

### ISSUE THREAD

**Issue by ghost** [JasonCreighton/snowy#2]
in Board.cpp line 436:

```
    // Update 50 move rule counter
    if(isCapture || isPawnMove) {
        m_NumReversiblePlies = 0;
    } else {
        ++m_NumReversiblePlies;     
}
```

This one doesn't consider castling as an irreversible move. Also, I think losing the castling right (king on e1, rook on h1 with castling right, but you move Ke2) should reset the counter, too. I will need to check the FIDE rules on this latter.

EDIT: this latter (the losing of the castling rights in an 50-move scenario) is astronomically rare in the wild, still, it would be nice to obey the rules totally.

**Comment by JasonCreighton** [comment]
I agree with you in spirit, but technically, [the FIDE rules](https://www.fide.com/fide/handbook.html?id=171&view=article) say the 50 move counter only resets on a pawn move or a capture. (See section 5.2 or 9.3)

Other irreversible moves, such as castling, or losing the right to castle, are not considered for the 50 move counter. Maybe I need to come up with a better name for that variable.
